# Generated by Django 3.1.7 on 2021-03-28 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210328_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Government Jobs', 'Government Jobs'), ('Fee Courses Online', 'fee courses online'), ('Government Exams', 'government exams'), ('Government Exams Result', 'government exams result'), ('Entrance exam', 'Entrance exam'), ('Job Notification', 'Job Notification'), ('Internship', 'Internship'), ('Work Form Home', 'work form home')], default='random', max_length=50),
        ),
    ]
